### ISSUE TITLE
Defining entry point 

### ISSUE THREAD

**Issue by shapeshed** [jacksoncage/node-docker#1]
The image currently assumes `app.js` as the entry point for the Node.js application. This isn't very portable and means that Node applications have to conform to an assumption in the container.

In my humble opinion there are two possible ways this could be made better.
### Environment variable

An environment variable could be exposed to allow the entry point to be set on `docker run`

``` bash
: "${ENTRY:=app.js}" # the app's entry point

# Start node.js application via nodemon
cd /var/www/
nodemon $ENTRY
```

You can then start the app with 

``` bash
sudo docker run -i -d -p 8080 -e ENTRY=server.js -v `pwd`/www:/var/www:ro jacksoncage/node 
```

If no environment variable is defined it will default to `app.js`.
### Use npm start

Npm allows authors to specify how an app should be started in package.json. The image could just call this script and delegate the responsibility to authors specifying this in package.json. A number of node PaaS providers follow this pattern.

``` javascript
{
  "name": "some-app",
  "version": "0.0.1",
  "author": "George Ornbo <george@shapeshed.com>",
  "description": "some description",
  "scripts": {
    "start": "nodemon app.js"
  }
}
```

If you think this is valid point let me know your preference and I can prepare a pull request :metal:. 

Personally I'd go with npm start.

**Comment by jacksoncage** [comment]
Thanks for the input @shapeshed 

It's a valid point and would defiantly suite if the docker file was more dynamic. In my perspective environment variables are more docker user friendly and npm start is more node developer friendly.

To be consistent within other Dockerfiles ([apache-docker](https://github.com/jacksoncage/apache-docker) - [varnish-docker](https://github.com/jacksoncage/varnish-docker)) I would like to go with the environment variable path. But to be most dynamic I would sugest  to use to environments variables `EXECUTER` and `APP`. Then default can be to use npm start and package.json structure or to just use nodemon app.js

``` bash
: "${EXECUTER:=npm}" # the executer to be used
: "${APP:=start}" # the app's entry point or executer command

# Start node.js application
cd /var/www/
$EXECUTER $APP
```

Then docker run could be both

``` bash
sudo docker run -i -d -p 8080 -e EXECUTER=nodemon -e APP=app.js -v `pwd`/www:/var/www:ro jacksoncage/node 
```

or

``` bash
sudo docker run -i -d -p 8080 -v `pwd`/www:/var/www:ro jacksoncage/node 
```

If you think this is a good idé please provide a pull request.
